
name: Terraform Deploy (Lab 1)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # enable OIDC to Azure

env:
  TF_VAR_resource_group_name: rg-existing
  TF_VAR_location: centralindia
  TF_VAR_storage_account_name: keshavlab1storage
  TF_VAR_key_vault_name: keshavlab1-kv
  TF_VAR_app_service_plan_name: keshavlab1-asp
  TF_VAR_web_app_name: keshavlab1-web

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: terraform init

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - run: terraform validate
      - run: terraform plan -out=tfplan
      - uses: actions/upload-artifact@v4
        with: { name: tfplan, path: tfplan }

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/download-artifact@v4
        with: { name: tfplan, path: . }
      - run: terraform apply -auto-approve tfplan
